### ISSUE TITLE
da_streets map issues

### ISSUE THREAD

**Issue by TomyLobo** [BSVino/DoubleAction#103]
1. The wooden ramp with the JR sign on it: You sometimes get stuck walking up the ramp. Can be reliably triggered by walking against one of the posts on the side, then turning towards the center to walk up the middle.
2. The map is a bit laggy with a lot of people, framerate-wise.

**Comment by Black-Stormy** [comment]
I fixed up the collision on that ramp and optimized the map a bit, among other updates

**Comment by TomyLobo** [comment]
I like the new pier, less likely to accidentally fall off :)
There are still some lighting issues with the new version, on the construction site side of the building.

Also, the old hand-optimized navmesh won't fit this new version.
Let's see if the generated one works well enough, or if the bots get stuck in all kinds of places again.

**Comment by Black-Stormy** [comment]
Let me know what you need done to the nav mesh, that way I can do it in the
future to other maps as I go

**Comment by TomyLobo** [comment]
i added jump points in all kinds of places where bots usually get stuck, connected various neighboring nodes that the generator had not connected because csgo bots are not supposed to climb or fall so deep.
In particular, if you have noticed bots jumping out of the window at the stairs on da_rooftops, check out the navmesh for that. They're true ninjas now :)

**Comment by Black-Stormy** [comment]
Got a link to read up on this? I assume it's just adding nodes in game and
re-generating the nav mesh

**Comment by TomyLobo** [comment]
I have no idea if that works. What I did was edit the navmesh after regenerating it.

**Comment by Black-Stormy** [comment]
Ok what nodes did you add and in any particular algorithm?

**Comment by TomyLobo** [comment]
like i said, i added the navmesh after generating it... manually.

**Comment by Black-Stormy** [comment]
Ah ok I have had a look at the navmesh on rooftops and I see what you mean.
Right now I am struggling with cubemaps, trying to fix up the HDR issue you
were seeing.

**Comment by Black-Stormy** [comment]
I think I know what's happening with the cubemaps. I think the map is
pulling its cubemaps from the materials/maps/[mapname] directory. When I
build cubemaps in the game that directory gets created. I think the
'materials/maps/da_megachat' directory may be the one you need to copy over
to fix cubemaps.

Also, when building cubemaps, the .bsp file gets saved in the da_info/maps
directory with the cubemaps bundled in. I copy this back to the dab/maps
directory (twice - HDR/LDR) and load it up but it still looks all bright if
I rename the map file. So I think maybe the game pulls from that
materials/maps folder? Can you test that?
