### ISSUE TITLE
da_morgendorffer map issues

### ISSUE THREAD

**Issue by TomyLobo** [BSVino/DoubleAction#104]
1. The doors behave badly in laggy environments, often getting you stuck in a critical situation. Maybe the simple situation would be to make those walk-through?
2. There are several boarded doors on this map. One of them is in a corridor next to a room with a milk carton on a desk. That door gets bots (and sometimes players) stuck. Can you make those walk-through?

**Comment by Black-Stormy** [comment]
I have uploaded Jespers overhaul of morgendorffer to my build, we shall playtest it and see how it goes. I have the vmf so can make adjustments as needed

**Comment by Black-Stormy** [comment]
fixed these issues, please playtest
