### ISSUE TITLE
da_megachat map issues

### ISSUE THREAD

**Issue by TomyLobo** [BSVino/DoubleAction#105]
1. You almost always get stuck if you spawn in the only spawn point with a clear window next to it. This could totally be a code problem, I just don't get what's so special about this spawn point. ![image](http://img.ctrlv.in/img/17/07/03/5959f70de3d16.jpg)
2. One of the briefcase delivery points (=info_player_deathmatch) is accessible through a wall. A solution would be to move it to the opposite wall ![image](http://img.ctrlv.in/img/17/07/02/5958d1044ed3e.jpg)

**Comment by Black-Stormy** [comment]
I have uploaded Jespers overhauled megachat which removes these issues but we'll need to playtest and see. I have the vmf too so can make adjustments.

**Comment by Black-Stormy** [comment]
have fixed these, please playtest
