### ISSUE TITLE
da_cocaine map issues

### ISSUE THREAD

**Issue by TomyLobo** [BSVino/DoubleAction#107]
1. It is possible to get out of the map in the courtyard
2. Bots get stuck on their way through the bathroom windows. I can't seem to make them duck reliably enough for them to not get stuck. Maybe if the window frame was flat inside, it'd work.

**Comment by TomyLobo** [comment]
All low-priority issues

**Comment by Black-Stormy** [comment]
I know you can get out of the map there, I left it in on purpose ;) I'd like to put something in the outside area that acknowledges the player having escaped the map

**Comment by Black-Stormy** [comment]
1. Changed the outside of the courtyard a touch, didn't block off the escape.
2. Raised the tops of those windows by like 32 units.

please test
