### ISSUE TITLE
da_trainingday map issues

### ISSUE THREAD

**Issue by TomyLobo** [BSVino/DoubleAction#109]
1. You can get stuck in prone under some wall posters. Maybe make those posters non-physical?
2. Sometimes the trains get stuck on bots, briefcases, hamburger boxes, you name it. Not sure if anything can be done about that.

**Comment by Black-Stormy** [comment]
1. Clipped the offending posters, and a couple other things
2. Can't do much other than stop the trains. I like the moving trains.

**Comment by Shigbeard** [comment]
Can't you detect if the train is stuck and if so, kill any players infront of the train?

**Comment by Black-Stormy** [comment]
The trains already have a trigger_kill on them. The ideal way to deal with this while keeping the trains is to make the trigger_kill cause the briefcase to respawn.

**Comment by BSVino** [comment]
I need to look to see if there's a code solution for the trains thing. Trains should just pass right through a briefcase.
