### ISSUE TITLE
da_rooftops map issues

### ISSUE THREAD

**Issue by TomyLobo** [BSVino/DoubleAction#110]
1. You can get stuck in prone under the fire extinguisher in the (upper) elevator. Maybe make that non-physical?
2. You can get stuck by sliding straight into the air conditioning exhaust thingy on the roof near the only ladder that's on the outside of a building. There are two more of these exhausts on the other side of the map. These share the same problem.

**Comment by Black-Stormy** [comment]
1. Clipped off the fire extinguisher please test
2. clipped and changed the exhaust thingy please test
