### ISSUE TITLE
Fast Weapon Switch doesn't work as intended when using slot hotkeys

### ISSUE THREAD

**Issue by Shigbeard** [BSVino/DoubleAction#113]
## Description of the problem
When Fast Weapon Switch is enabled and the player attempts to switch weapons using slot hotkeys (such as 1, 2, 3, 4, 5), the first attempt the player makes at firing that weapon will fail (it will instead result in a single click sound, and no bullets will fire). This also occurs if the selected weapon is already active.

This issue does not occur if the player attempts to switch weapons using the scroll wheel (`invprev` and `invnext` commands). It is unknown (or rather, untested) if this occurs on the `lastinv` command, however that is highly likely given the behavior of `lastinv`.

## What is the intended behavior
When Fast Weapon Switch is enabled and the player attempts to switch weapons using slot hotkeys (such as 1, 2, 3, 4, 5), the weapon will immediately switch and be ready to fire immediately without the player having to confirm the weapon switching action.

## What do you think is the cause of this problem
I feel that something has been done to alter the way weapon switching is handled for when Fast Weapon Switching is disabled, but somehow while this behavior was circumvented for scrolling with Fast Weapon Switching enabled, it was not circumvented for slot commands like `slot1`, `slot2`, `slot3` etc.

This is further implied by the fact that the aforementioned click sound that is heard when attempting to fire a weapon after switching is the same sound you hear when you confirm the switch to a weapon with Fast Weapon Switching disabled, and given the same action generates this sound (clicking with the left mouse button), it would be safe to assume this is what is happening.

## How is the issue a problem for the development team?
This faulty behavior does not occur in any other source engine game to the best of my knowledge, including mods such as Fistful of Frags and E.Y.E Divine Cybermancy.

**Comment by BSVino** [comment]
Thanks for filing such a detailed bug report, Shigbeard. Better than many of the QA folks at my job ;)

**Comment by TomyLobo** [comment]
"Does not work - please look into this"?

**Comment by Shigbeard** [comment]
Update: `lastinv` confirmed to produce same effects.
