### ISSUE TITLE
I can't hear my friend's gun 99% of the time

### ISSUE THREAD

**Issue by LAX1DUDE** [BSVino/DoubleAction#120]
it's really freaking annoying because then I can't tell when he's shooting me without glancing at the health constantly. can you plz fix it?

**Comment by TomyLobo** [comment]
I have no idea what causes this. It seems to depend on the amount of shots fired since the last restart/reconnect or something.

**Comment by LAX1DUDE** [comment]
It seems to only happen when my back is turned to the source so it probably has something to do with the way the sound's volume is being calculated

**Comment by TomyLobo** [comment]
hmm, to me it , happens to me regardless of direction
maybe you have a different issue.
can you disable surround sound in the options?
just set it to headphones

**Comment by LAX1DUDE** [comment]
I think that fixed it. thanks
