### ISSUE TITLE
Auto-Switch sometimes selects a grenade

### ISSUE THREAD

**Issue by TomyLobo** [BSVino/DoubleAction#42]
When dropping a weapon, grenades are selected, although they are not supposed to be selectable, have no viewmodel and are usually not desirable to have selected.

Example:

1. Spawn with Stallion, Sentinel and a grenade
2. Drop the Stallion
    * Expected: the Sentinel is selected
    * Actual: the grenade is selected

**Comment by TomyLobo** [comment]
The cause for this issue is that the "weight" field in "dab/scripts/weapon_grenade.txt" is set to "10", which prioritizes it higher than both the Sentinel and the Stallion and at the same level as the Undertaker.

According to this article, we're misusing the weight flag here:
https://developer.valvesoftware.com/wiki/Weapon_script

This means we'll have to switch the entire slot-weight system over to a separate field.

**Comment by BSVino** [comment]
I rewrote the weapon selection so we can use the weight flag for anything we want. Valve has a different weapons system then we have so they have different weapon switching mechanics requirements. Our weapons do have an actual weight ie number of slots. So I don't think it's necessary to move weapon weights over to a separate field. I would say maybe make a new "not deployable" field or something and check that at the appropriate place?

**Comment by TomyLobo** [comment]
That'll be a change to code outside the mp/src/game/*/da/ subdirectories.
That's something I wanted to avoid :)

There's AllowsAutoSwitchTo and with a small patch, that seems to work nicely. I'll make a PR with that
