### ISSUE TITLE
Add a cvar to control pickup behaviour

### ISSUE THREAD

**Issue by TomyLobo** [BSVino/DoubleAction#93]
`cl_pickup_dropweapons 0|1`
default: 1
0 - Do not drop weapons in order to accomodate weapons picked up from the ground.
1 - Drop weapons in order to accomodate weapons picked up from the ground.

**Comment by Shigbeard** [comment]
Alternative name suggestions:

`cl_pickup_replace` <-- personal fav
`cl_pickup_dropweapons`

**Comment by TomyLobo** [comment]
I'll use cl_pickup_dropweapons
